import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer, request as httpRequest } from 'node:http';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApi } from './api.mjs';
import { NETWORKS } from './data.mjs';
import { publicMeetingVenues } from './geography.mjs';
import { DatabaseSync } from 'node:sqlite';

async function fixture(t,options={}) {
  let time=Date.parse('2026-09-13T04:00:00Z');
  const api=createApi({dbPath:':memory:',now:()=>time,...options});
  const server=createServer((req,res)=>{options.observeRequest?.(req);api.handle(req,res).then(handled=>{if(!handled){res.statusCode=404;res.end();}});});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const base=`http://127.0.0.1:${server.address().port}`;
  t.after(async()=>{await new Promise(resolve=>server.close(resolve));api.close();});
  function client(){let cookie='';return {async call(path,method='GET',body,custom={}){const headers={...(cookie?{Cookie:cookie}:{}),...(method==='GET'?{}:{Origin:base,'Content-Type':'application/json'}),...custom};const res=await fetch(base+path,{method,headers,...(body!==undefined?{body:JSON.stringify(body)}:{})});const next=res.headers.get('set-cookie');if(next)cookie=next.split(';')[0];return {status:res.status,headers:res.headers,body:await res.json()};},get cookie(){return cookie;}};}
  return {client,advance:ms=>time+=ms,api,base};
}

test('all four education networks are server authorization boundaries for every object type',async t=>{
  const f=await fixture(t),clients={},states={};
  for(const network of NETWORKS){clients[network]=f.client();assert.equal((await clients[network].call('/api/demo','POST',{network})).status,200);states[network]=(await clients[network].call('/api/state')).body;assert.ok(states[network].activities.length>=8);for(const item of [...states[network].activities,...states[network].people,...states[network].circles,...states[network].tutors])assert.equal(item.network,network);assert.equal(states[network].meta.network,network);}
  for(const network of NETWORKS){for(const foreign of NETWORKS.filter(x=>x!==network)){
    const client=clients[network],s=states[foreign];
    const cases=[['/api/activities/'+s.activities[0].id,'GET'],['/api/activities/'+s.activities[0].id+'/join','POST',{}],['/api/activities/'+s.activities[0].id+'/save','POST',{}],['/api/circles/'+s.circles[0].id+'/join','POST',{}],['/api/connections','POST',{personId:s.people[0].id,action:'connect'}],['/api/messages/'+s.people[0].id,'GET'],['/api/messages/'+s.people[0].id,'POST',{text:'Hello'}],['/api/tutors/'+s.tutors[0].id+'/request','POST',{date:'2026-09-15',time:'15:00'}],['/api/blocks','POST',{personId:s.people[0].id}],['/api/reports','POST',{targetId:s.activities[0].id,reason:'Unsafe'}],['/api/telegram/consent','POST',{personId:s.people[0].id,consent:true}]];
    for(const args of cases){const result=await client.call(...args);assert.equal(result.status,404,`${network} → ${foreign} ${args[0]}: ${JSON.stringify(result.body)}`);}
  }}
});

test('origin/session checks and immutable identity prevent request tampering',async t=>{
  const f=await fixture(t),c=f.client();assert.equal((await c.call('/api/state')).status,401);
  assert.equal((await c.call('/api/demo','POST',{}, {Origin:'https://evil.example'})).status,403);
  const login=await c.call('/api/demo','POST',{});assert.match(login.headers.get('set-cookie'),/HttpOnly; SameSite=Lax/);assert.equal(c.cookie.length,77);
  assert.equal((await c.call('/api/profile','PATCH',{network:'university'})).status,400);
  assert.equal((await c.call('/api/profile','PATCH',{institutionId:'nus'})).status,400);
  assert.equal((await c.call('/api/profile','PATCH',{ageBand:'under18'})).status,400);
  assert.equal((await c.call('/api/profile','PATCH',{bio:'Text me at 9123 4567'})).status,400);
  const state=(await c.call('/api/state')).body;assert.ok(!('email' in state.people[0]));assert.ok(!('ageBand' in state.people[0]));assert.ok(!('telegramUsername' in state.people[0]));assert.ok(!('settings' in state.people[0]));
  assert.equal((await c.call('/api/logout','POST',{})).status,200);assert.equal((await c.call('/api/state')).status,401);
});

test('activities persist, require public network locations and enforce idempotent capacity',async t=>{
  const f=await fixture(t),c=f.client();await c.call('/api/demo','POST',{});const locs=(await c.call('/api/locations')).body.locations;assert.ok(locs.every(x=>x.network==='polytechnic'));
  const input={category:'sports',title:'Friendly doubles',description:'Bring a racket and meet at the sports centre.',date:'2026-09-14',time:'17:30',locationId:locs[0].id,capacity:2};
  assert.equal((await c.call('/api/activities','POST',{...input,network:'university'})).status,403);
  assert.equal((await c.call('/api/activities','POST',{...input,locationId:'nus-library'})).status,400);
  assert.equal((await c.call('/api/activities','POST',{...input,locationId:'home-address'})).status,400);
  assert.equal((await c.call('/api/activities','POST',{...input,date:'2026-02-31'})).status,400);
  const created=await c.call('/api/activities','POST',input);assert.equal(created.status,201);assert.equal(created.body.activity.network,'polytechnic');assert.equal(created.body.activity.participants.length,1);
  const other=f.client();const otp=await other.call('/api/auth/start','POST',{institutionId:'sp',email:'second@ichat.sp.edu.sg',ageBand:'18plus'});assert.equal(otp.status,200);await other.call('/api/auth/verify','POST',{challengeId:otp.body.challengeId,code:otp.body.demoCode});
  const url='/api/activities/'+created.body.activity.id;assert.equal((await other.call(url+'/join','POST',{})).status,200);const repeated=await other.call(url+'/join','POST',{});assert.equal(repeated.status,200);assert.equal(repeated.body.activity.participants.length,2);
  const third=f.client(),otp3=await third.call('/api/auth/start','POST',{institutionId:'np',email:'third@connect.np.edu.sg'});await third.call('/api/auth/verify','POST',{challengeId:otp3.body.challengeId,code:otp3.body.demoCode});assert.equal((await third.call(url+'/join','POST',{})).status,409);
  assert.equal((await other.call(url+'/leave','POST',{})).status,200);assert.equal((await third.call(url+'/join','POST',{})).status,200);
  const saved=await third.call(url+'/save','POST',{});assert.equal(saved.body.activity.saved,true);assert.equal((await third.call(url+'/save','POST',{})).body.activity.saved,false);
});

test('mutual consent gates messaging, blocks apply in both directions and no contact leaks',async t=>{
  const f=await fixture(t),c=f.client();await c.call('/api/demo','POST',{});
  assert.equal((await c.call('/api/messages/polytechnic-p1','GET')).status,403);
  const match=await c.call('/api/connections','POST',{personId:'polytechnic-p1',action:'connect'});assert.equal(match.body.mutual,true);
  assert.equal((await c.call('/api/messages/polytechnic-p1','POST',{text:'See you at badminton!'})).status,201);
  assert.equal((await c.call('/api/messages/polytechnic-p1','POST',{text:'My Telegram is @testuser'})).status,400);
  assert.equal((await c.call('/api/messages/polytechnic-p1')).body.messages.length,1);
  await c.call('/api/telegram/consent','POST',{personId:'polytechnic-p1',consent:true});await c.call('/api/blocks','POST',{personId:'polytechnic-p1'});
  assert.equal((await c.call('/api/messages/polytechnic-p1')).status,403);assert.equal((await c.call('/api/messages/polytechnic-p1','POST',{text:'Hi'})).status,403);assert.equal((await c.call('/api/telegram/consent','POST',{personId:'polytechnic-p1',consent:true})).status,403);
  const state=(await c.call('/api/state')).body;assert.ok(!state.people.some(p=>p.id==='polytechnic-p1'));assert.ok(!state.conversations.some(p=>p.personId==='polytechnic-p1'));assert.ok(state.activities.every(a=>!a.participants.includes('polytechnic-p1')));
  assert.equal((await c.call('/api/blocks/polytechnic-p1','DELETE')).status,200);assert.equal((await c.call('/api/messages/polytechnic-p1')).status,200);
});

test('OTP rejects false domains, guesses, replay, expiry; live verification fails closed',async t=>{
  const f=await fixture(t),c=f.client();for(const email of ['me@gmail.com','me@ichat.sp.edu.sg.evil.com','me@sp.edu.sg'])assert.equal((await c.call('/api/auth/start','POST',{institutionId:'sp',email})).status,400);
  let start=await c.call('/api/auth/start','POST',{institutionId:'sp',email:'real@ichat.sp.edu.sg'});assert.match(start.body.demoCode,/^\d{6}$/);assert.notEqual(start.body.maskedEmail,'real@ichat.sp.edu.sg');
  assert.equal((await c.call('/api/auth/start','POST',{institutionId:'sp',email:'real@ichat.sp.edu.sg'})).status,429);
  const bad=start.body.demoCode==='000000'?'000001':'000000';assert.equal((await c.call('/api/auth/verify','POST',{challengeId:start.body.challengeId,code:bad})).status,400);
  assert.equal((await c.call('/api/auth/verify','POST',{challengeId:start.body.challengeId,code:start.body.demoCode})).status,200);
  assert.equal((await c.call('/api/auth/verify','POST',{challengeId:start.body.challengeId,code:start.body.demoCode})).status,400);
  start=await c.call('/api/auth/start','POST',{institutionId:'np',email:'expire@connect.np.edu.sg'});f.advance(600001);assert.equal((await c.call('/api/auth/verify','POST',{challengeId:start.body.challengeId,code:start.body.demoCode})).status,400);
  start=await c.call('/api/auth/start','POST',{institutionId:'tp',email:'lock@student.tp.edu.sg'});for(let i=0;i<5;i++)await c.call('/api/auth/verify','POST',{challengeId:start.body.challengeId,code:start.body.demoCode==='000000'?'000001':'000000'});assert.equal((await c.call('/api/auth/verify','POST',{challengeId:start.body.challengeId,code:start.body.demoCode})).status,400);
  const live=await fixture(t,{demoMode:false,resendApiKey:null,mailFrom:null}),lc=live.client();assert.equal((await lc.call('/api/demo','POST',{})).status,404);assert.equal((await lc.call('/api/auth/start','POST',{institutionId:'sp',email:'student@ichat.sp.edu.sg'})).status,503);
});

test('full MOE institution directory and demo onboarding works in four networks',async t=>{
  const f=await fixture(t),c=f.client();for(const network of NETWORKS){const result=await c.call('/api/institutions?network='+network);assert.equal(result.status,200);const rows=result.body.institutions;assert.ok(rows.length>=(network==='secondary'?140:network==='jc_mi'?20:network==='polytechnic'?5:6),`${network}: ${rows.length}`);const school=rows[0],start=await c.call('/api/auth/start','POST',{institutionId:school.id,email:`student@${school.domains[0]}`,ageBand:network==='secondary'||network==='jc_mi'?'under18':'18plus'});assert.equal(start.status,200,JSON.stringify(start.body));const verified=await c.call('/api/auth/verify','POST',{challengeId:start.body.challengeId,code:start.body.demoCode});assert.equal(verified.status,200);assert.equal(verified.body.user.network,network);if(network==='secondary'||network==='jc_mi'){assert.equal(verified.body.user.settings.discoverable,false);assert.equal(verified.body.user.settings.allowInvites,false);assert.equal(verified.body.user.settings.activityVisibility,'connections');}}
});

test('reflections are private, tutoring requests persist, circle join is idempotent',async t=>{
  const f=await fixture(t),c=f.client();await c.call('/api/demo','POST',{});const first=(await c.call('/api/state')).body,activityId=first.activities[0].id;
  assert.equal((await c.call('/api/reflections','POST',{text:'Not joined',tags:[],activityId})).status,403);
  await c.call('/api/activities/'+activityId+'/join','POST',{});const reflect=await c.call('/api/reflections','POST',{text:'I enjoyed meeting someone new.',tags:['Met someone new'],activityId});assert.equal(reflect.status,201);
  const circleId=first.circles[0].id;const join1=await c.call('/api/circles/'+circleId+'/join','POST',{}),join2=await c.call('/api/circles/'+circleId+'/join','POST',{});assert.equal(join1.body.circle.memberCount,join2.body.circle.memberCount);
  const request=await c.call('/api/tutors/'+first.tutors[0].id+'/request','POST',{date:'2026-09-16',time:'15:00',message:'Could we cover SQL joins?'});assert.equal(request.status,201);
  const state=(await c.call('/api/state')).body;assert.equal(state.journey.reflections.length,1);assert.equal(state.requests.length,1);assert.equal(state.journey.stats.sports,1);assert.ok(state.people.every(p=>!p.reflections));
});

test('SQLite persists profile and session across API restarts',async t=>{
  const folder=mkdtempSync(join(tmpdir(),'kaki-test-'));const dbPath=join(folder,'test.sqlite');
  const f=await fixture(t,{dbPath}),c=f.client();await c.call('/api/demo','POST',{});await c.call('/api/profile','PATCH',{bio:'A persistent new bio.'});const other=createApi({dbPath,now:()=>Date.parse('2026-09-13T04:00:00Z')});const server=createServer((req,res)=>other.handle(req,res));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(async()=>{await new Promise(resolve=>server.close(resolve));other.close();});t.after(()=>rmSync(folder,{recursive:true,force:true}));const res=await fetch(`http://127.0.0.1:${server.address().port}/api/state`,{headers:{Cookie:c.cookie}});assert.equal(res.status,200);assert.equal((await res.json()).user.bio,'A persistent new bio.');
});

test('membership privacy and under-18 boundaries apply on the server',async t=>{
  const f=await fixture(t),jamie=f.client(),adult=f.client(),younger=f.client();await jamie.call('/api/demo','POST',{});
  const login=async(c,email,ageBand)=>{const challenge=(await c.call('/api/auth/start','POST',{institutionId:'sp',email,ageBand})).body;return (await c.call('/api/auth/verify','POST',{challengeId:challenge.challengeId,code:challenge.demoCode})).body.user;};
  const adultUser=await login(adult,'private@ichat.sp.edu.sg','18plus');await adult.call('/api/activities/polytechnic-a1/join','POST',{});
  let details=(await jamie.call('/api/activities/polytechnic-a1')).body;assert.ok(details.members.some(p=>p.id===adultUser.id));const count=details.activity.participantCount;
  await adult.call('/api/profile','PATCH',{settings:{activityVisibility:'private',discoverable:false}});details=(await jamie.call('/api/activities/polytechnic-a1')).body;assert.ok(!details.members.some(p=>p.id===adultUser.id));assert.ok(!details.activity.participants.includes(adultUser.id));assert.equal(details.activity.participantCount,count);assert.ok(!(await jamie.call('/api/state')).body.people.some(p=>p.id===adultUser.id));
  await login(younger,'younger@ichat.sp.edu.sg','under18');const state=(await younger.call('/api/state')).body;assert.equal(state.people.length,0);assert.equal(state.activities.length,0);assert.equal(state.circles.length,0);assert.equal(state.tutors.length,0);
  for(const [path,method,body] of [['/api/activities/polytechnic-a1','GET'],['/api/activities/polytechnic-a1/join','POST',{}],['/api/circles/polytechnic-c1/join','POST',{}],['/api/connections','POST',{personId:'polytechnic-p1',action:'connect'}],['/api/tutors/polytechnic-t1/request','POST',{date:'2026-09-15',time:'15:00'}]])assert.equal((await younger.call(path,method,body)).status,403,path);
  const saved=await adult.call('/api/profile','PATCH',{settings:{telegramMatches:true,telegramNotifications:true}});assert.equal(saved.status,200);assert.equal(saved.body.user.settings.telegramMatches,true);assert.equal((await adult.call('/api/state')).body.meta.telegramAvailable,false);
});

test('unconfigured hosts and hostile avatar/profile fields are rejected',async t=>{
  const f=await fixture(t),c=f.client();const hostile=await new Promise((resolve,reject)=>{const req=httpRequest(f.base+'/api/health',{headers:{Host:'attacker.example'}},res=>{res.resume();res.on('end',()=>resolve(res.statusCode));});req.on('error',reject);req.end();});assert.equal(hostile,403);assert.equal((await c.call('/api/demo','POST',{}, {Origin:'http://attacker.example'})).status,403);
  await c.call('/api/demo','POST',{});
  for(const avatar of ['data:image/svg+xml,<svg onload=alert(1)>','https://attacker.example/avatar.png','javascript:alert(1)','/assets/kaki/../../data/kaki.sqlite','/assets/kaki/avatar-7.webp'])assert.equal((await c.call('/api/profile','PATCH',{avatar})).status,400);
  for(const field of ['verified','emailVerified','enrolmentVerified','ageVerified','telegramUsername','email','network','ageBand'])assert.equal((await c.call('/api/profile','PATCH',{[field]:true})).status,400,field);
  assert.equal((await c.call('/api/profile','PATCH',{avatar:'/assets/kaki/avatar-2.webp'})).status,200);
  assert.equal((await c.call('/api/profile','PATCH',JSON.parse('{"settings":{"__proto__":{"discoverable":true}}}'))).status,400);
});

test('live email ownership does not claim enrolment or age verification and never returns an OTP',async t=>{
  const originalFetch=globalThis.fetch;let deliveredCode;
  t.mock.method(globalThis,'fetch',async(input,options)=>{if(input==='https://api.resend.com/emails'){const mail=JSON.parse(options.body);deliveredCode=/code is (\d{6})/.exec(mail.text)[1];return new Response(JSON.stringify({id:'local-provider-test'}),{status:200});}return originalFetch(input,options);});
  const f=await fixture(t,{demoMode:false,resendApiKey:'test-provider',mailFrom:'test@example.test'}),c=f.client();
  const start=await c.call('/api/auth/start','POST',{institutionId:'sp',email:'mailbox@ichat.sp.edu.sg',ageBand:'18plus'});assert.equal(start.status,200);assert.equal(start.body.demoCode,undefined);assert.match(deliveredCode,/^\d{6}$/);
  const verify=await c.call('/api/auth/verify','POST',{challengeId:start.body.challengeId,code:deliveredCode});assert.equal(verify.status,200);assert.equal(verify.body.user.emailVerified,true);assert.equal(verify.body.user.enrolmentVerified,false);assert.equal(verify.body.user.ageVerified,false);assert.equal(verify.body.user.verified,false);assert.equal(verify.body.user.verificationMethod,'email');
  const state=(await c.call('/api/state')).body;assert.equal(state.people.length,0);assert.equal(state.activities.length,0);assert.equal(state.circles.length,0);
  const school=(await c.call('/api/institutions?network=secondary')).body.institutions[0];assert.equal((await c.call('/api/auth/start','POST',{institutionId:school.id,email:`mailbox@${school.domains[0]}`,ageBand:'under18'})).status,503);
  assert.equal((await c.call('/api/auth/start','POST',{institutionId:'smu',email:'staff@smu.edu.sg',ageBand:'18plus'})).status,503);
});

test('public profile allowlist excludes future private fields and block revokes external consent',async t=>{
  const folder=mkdtempSync(join(tmpdir(),'kaki-private-')),dbPath=join(folder,'private.sqlite');const f=await fixture(t,{dbPath});t.after(()=>rmSync(folder,{recursive:true,force:true}));
  const db=new DatabaseSync(dbPath),row=db.prepare('SELECT data FROM objects WHERE kind=? AND id=?').get('profile','polytechnic-p1'),profile=JSON.parse(row.data);profile.privateNotes='never public';profile.emergencyContact='never public';profile.reflections=[{text:'never public'}];db.prepare('UPDATE objects SET data=? WHERE kind=? AND id=?').run(JSON.stringify(profile),'profile',profile.id);db.close();
  const c=f.client();await c.call('/api/demo','POST',{});const state=(await c.call('/api/state')).body;for(const person of [state.people.find(p=>p.id===profile.id),state.activities[0].host]){assert.equal(person.privateNotes,undefined);assert.equal(person.emergencyContact,undefined);assert.equal(person.reflections,undefined);assert.equal(person.email,undefined);}
  await c.call('/api/connections','POST',{personId:profile.id,action:'connect'});await c.call('/api/telegram/consent','POST',{personId:profile.id,consent:true});const inject=new DatabaseSync(dbPath);inject.prepare('INSERT INTO relations(kind,sender,recipient,data) VALUES(?,?,?,?)').run('telegram-consent',profile.id,'polytechnic-p0','{}');inject.close();
  assert.equal((await c.call('/api/telegram/consent','POST',{personId:profile.id,consent:true})).body.mutual,true);await c.call('/api/reports','POST',{targetId:profile.id,reason:'Unwanted contact',block:true});await c.call('/api/blocks/'+profile.id,'DELETE');assert.equal((await c.call('/api/telegram/consent','POST',{personId:profile.id,consent:true})).body.mutual,false);
});

test('live mode refuses a legacy demo database without the new mode marker',async t=>{
  const folder=mkdtempSync(join(tmpdir(),'kaki-mode-')),dbPath=join(folder,'mode.sqlite');t.after(()=>rmSync(folder,{recursive:true,force:true}));const demo=createApi({dbPath});demo.close();const db=new DatabaseSync(dbPath);db.prepare('DELETE FROM meta WHERE key=?').run('data-mode');db.close();assert.throws(()=>createApi({dbPath,demoMode:false}),/existing database contains demo records/);
});

test('tutor inbox and request lifecycle enforce recipient, requester, privacy and idempotency',async t=>{
  const folder=mkdtempSync(join(tmpdir(),'kaki-tutor-')),dbPath=join(folder,'tutor.sqlite');const f=await fixture(t,{dbPath});t.after(()=>rmSync(folder,{recursive:true,force:true}));const requester=f.client(),recipient=f.client(),stranger=f.client(),foreign=f.client();await requester.call('/api/demo','POST',{});await foreign.call('/api/demo','POST',{network:'university'});
  const login=async(c,email)=>{const start=(await c.call('/api/auth/start','POST',{institutionId:'sp',email,ageBand:'18plus'})).body;return (await c.call('/api/auth/verify','POST',{challengeId:start.challengeId,code:start.demoCode})).body.user;};
  const tutorUser=await login(recipient,'tutor-test@ichat.sp.edu.sg');await login(stranger,'stranger-test@ichat.sp.edu.sg');
  const tutor={id:'test-inbox-tutor',network:'polytechnic',personId:tutorUser.id,subject:'Database Systems',price:0};const db=new DatabaseSync(dbPath);db.prepare('INSERT INTO objects(kind,id,network,data) VALUES(?,?,?,?)').run('tutor',tutor.id,tutor.network,JSON.stringify(tutor));db.close();
  const make=async(message,date='2026-09-16')=>requester.call('/api/tutors/'+tutor.id+'/request','POST',{date,time:'15:00',message});
  const first=await make('Help with SQL joins');assert.equal(first.status,201);const requestId=first.body.request.id;const again=await make('Help with SQL joins');assert.equal(again.status,200);assert.equal(again.body.request.id,requestId);
  const incoming=(await recipient.call('/api/state')).body.incomingRequests;assert.equal(incoming.length,1);assert.equal(incoming[0].requester.name,'Jamie Tan');assert.equal(incoming[0].requester.email,undefined);assert.equal(incoming[0].requester.settings,undefined);assert.equal(incoming[0].recipientId,tutorUser.id);assert.equal((await stranger.call('/api/state')).body.incomingRequests.length,0);assert.equal((await stranger.call('/api/state')).body.requests.length,0);
  const patch=(c,status,id=requestId)=>c.call('/api/tutor-requests/'+id,'PATCH',{status});
  assert.equal((await patch(requester,'accepted')).status,403);assert.equal((await patch(recipient,'cancelled')).status,403);assert.equal((await patch(stranger,'accepted')).status,404);assert.equal((await patch(foreign,'accepted')).status,404);
  const accepted=await patch(recipient,'accepted');assert.equal(accepted.status,200);assert.equal(accepted.body.request.status,'accepted');assert.equal((await patch(recipient,'accepted')).body.request.updatedAt,accepted.body.request.updatedAt);assert.equal((await patch(requester,'cancelled')).status,409);assert.equal((await patch(recipient,'declined')).status,409);assert.equal((await requester.call('/api/state')).body.requests.find(r=>r.id===requestId).status,'accepted');
  const second=(await make('Help with database indexes','2026-09-17')).body.request;assert.equal((await patch(recipient,'declined',second.id)).status,200);assert.equal((await patch(recipient,'declined',second.id)).status,200);assert.equal((await patch(recipient,'accepted',second.id)).status,409);
  const third=(await make('Review my practice questions','2026-09-18')).body.request;assert.equal((await patch(requester,'cancelled',third.id)).status,200);assert.equal((await patch(requester,'cancelled',third.id)).status,200);assert.equal((await patch(recipient,'accepted',third.id)).status,409);
  const fourth=(await make('A little more practice','2026-09-19')).body.request;await requester.call('/api/blocks','POST',{personId:tutorUser.id});assert.equal((await recipient.call('/api/state')).body.incomingRequests.length,0);assert.equal((await patch(recipient,'accepted',fourth.id)).status,403);assert.equal((await make('Another request','2026-09-20')).status,403);
});

async function signupClient(f,email,ageBand='18plus',institutionId='sp') {
  const client=f.client(),challenge=(await client.call('/api/auth/start','POST',{institutionId,email,ageBand})).body;
  const verified=await client.call('/api/auth/verify','POST',{challengeId:challenge.challengeId,code:challenge.demoCode});
  assert.equal(verified.status,200);return {client,user:verified.body.user};
}

test('study roles share capacity, remain private, and mentor feedback requires a completed peer session',async t=>{
  const f=await fixture(t),host=f.client();await host.call('/api/demo','POST',{});const peer=await signupClient(f,'study-peer@ichat.sp.edu.sg'),other=await signupClient(f,'study-other@ichat.sp.edu.sg');
  const input={category:'study',role:'mentor',title:'SQL peer workshop',description:'Bring a practice query and learn together.',date:'2026-09-13',time:'13:00',locationId:'sp-library',capacity:2,subject:'Database Systems'};
  const created=await host.call('/api/activities','POST',input);assert.equal(created.status,201);let a=created.body.activity;assert.equal(a.myRole,'mentor');assert.deepEqual(a.roleCounts,{peer:0,mentor:1});assert.ok(a.locationDetails.lat);assert.equal(a.locationDetails.precision,'venue');
  let profile=(await host.call('/api/state')).body.user;assert.equal(profile.mentorStats.registered,true);assert.equal(profile.mentorStats.isNew,true);assert.equal(profile.mentorStats.sessionCount,0);assert.equal(profile.mentorStats.daysSinceFirstMentorship,null);assert.equal(profile.mentorStats.firstMentorshipAt,null);
  for(const role of ['teacher','',null])assert.equal((await peer.client.call('/api/activities/'+a.id+'/join','POST',{role})).status,400);
  a=(await peer.client.call('/api/activities/'+a.id+'/join','POST',{role:'peer'})).body.activity;assert.equal(a.participantCount,2);assert.deepEqual(a.roleCounts,{peer:1,mentor:1});
  a=(await peer.client.call('/api/activities/'+a.id+'/join','POST',{role:'mentor'})).body.activity;assert.equal(a.participantCount,2);assert.deepEqual(a.roleCounts,{peer:0,mentor:2});assert.equal((await other.client.call('/api/activities/'+a.id+'/join','POST',{role:'peer'})).status,409);
  await peer.client.call('/api/activities/'+a.id+'/join','POST',{role:'peer'});assert.equal((await peer.client.call('/api/mentors/polytechnic-p0/like','POST',{})).status,403);assert.equal((await host.call('/api/mentors/polytechnic-p0/like','POST',{})).status,400);
  await host.call('/api/profile','PATCH',{settings:{activityVisibility:'private'}});const privateView=(await peer.client.call('/api/activities/'+a.id)).body.activity;assert.equal(privateView.participantRoles['polytechnic-p0'],undefined);assert.equal(privateView.participantRoleJoinedAt,undefined);assert.equal(privateView.participantJoinedAt,undefined);assert.equal(privateView.roleCounts.mentor,1);
  f.advance(3600000);profile=(await host.call('/api/state')).body.user;assert.equal(profile.mentorStats.isNew,true);assert.equal(profile.mentorStats.sessionCount,0);assert.equal(profile.mentorStats.firstMentorshipAt,'2026-09-13T05:00:00.000Z');assert.equal(profile.mentorStats.daysSinceFirstMentorship,0);
  f.advance(2*3600000+1);profile=(await host.call('/api/state')).body.user;assert.equal(profile.mentorStats.isNew,false);assert.equal(profile.mentorStats.sessionCount,1);
  let like=await peer.client.call('/api/mentors/polytechnic-p0/like','POST',{});assert.equal(like.status,200);assert.equal(like.body.liked,true);assert.equal(like.body.mentorStats.likeCount,1);assert.equal((await peer.client.call('/api/mentors/polytechnic-p0/like','POST',{})).body.mentorStats.likeCount,0);
  assert.equal((await other.client.call('/api/mentors/polytechnic-p0/like','POST',{})).status,403);assert.equal((await peer.client.call('/api/activities/'+a.id+'/join','POST',{role:'mentor'})).status,409);assert.equal((await peer.client.call('/api/activities/'+a.id+'/leave','POST',{})).status,409);
  const foreign=f.client();await foreign.call('/api/demo','POST',{network:'university'});assert.equal((await foreign.call('/api/mentors/polytechnic-p0/like','POST',{})).status,404);
  f.advance(86400000);profile=(await host.call('/api/state')).body.user;assert.equal(profile.mentorStats.daysSinceFirstMentorship,1);assert.equal(profile.mentorStats.firstMentorshipAt,'2026-09-13T05:00:00.000Z');
});

test('clubs enforce membership, network, age and blocked-author filtering without opening DMs',async t=>{
  let observeRequest;const f=await fixture(t,{observeRequest:req=>observeRequest?.(req)}),owner=f.client();await owner.call('/api/demo','POST',{});const member=await signupClient(f,'club-member@ichat.sp.edu.sg'),younger=await signupClient(f,'club-younger@ichat.sp.edu.sg','under18'),secondMember=await signupClient(f,'club-second@ichat.sp.edu.sg'),foreign=f.client();await foreign.call('/api/demo','POST',{network:'university'});
  const create=await owner.call('/api/circles','POST',{name:'Weekend explorers',interest:'Photography',description:'Small photo walks and relaxed conversations.',ageBand:'under18'});assert.equal(create.status,201);const c=create.body.circle;assert.equal(c.ownerId,'polytechnic-p0');assert.equal(c.ageBand,'18plus');assert.equal(c.network,'polytechnic');
  assert.equal((await member.client.call('/api/circles/'+c.id+'/messages')).status,200);assert.equal((await member.client.call('/api/circles/'+c.id+'/messages','POST',{text:'Hello everyone'})).status,403);
  assert.equal((await foreign.call('/api/circles/'+c.id)).status,404);assert.equal((await younger.client.call('/api/circles/'+c.id+'/join','POST',{})).status,403);assert.equal((await owner.call('/api/circles','POST',{name:'Wrong network',interest:'Games',description:'A little gathering together.',network:'university'})).status,403);
  const joins=await Promise.all([member.client.call('/api/circles/'+c.id+'/join','POST',{}),secondMember.client.call('/api/circles/'+c.id+'/join','POST',{})]);assert.ok(joins.every(r=>r.status===200));assert.equal((await owner.call('/api/circles/'+c.id)).body.circle.memberCount,3);const message=await member.client.call('/api/circles/'+c.id+'/messages','POST',{text:'A Saturday photo walk sounds good!'});assert.equal(message.status,201);assert.equal(message.body.message.author.email,undefined);assert.equal(message.body.message.author.id,member.user.id);
  assert.equal((await member.client.call('/api/circles/'+c.id+'/messages','POST',{text:'Message me at 9123 4567'})).status,400);assert.equal((await member.client.call('/api/messages/polytechnic-p0','POST',{text:'Direct message'})).status,403);
  assert.equal((await owner.call('/api/circles/'+c.id+'/messages')).body.messages.length,1);
  let arrived;const started=new Promise(resolve=>arrived=resolve);observeRequest=req=>{if(req.method==='POST'&&req.url==='/api/circles/'+c.id+'/messages')arrived();};
  const delayedBody=JSON.stringify({text:'A slow message after access was revoked'});let delayedRequest;const delayedResponse=new Promise((resolve,reject)=>{delayedRequest=httpRequest(f.base+'/api/circles/'+c.id+'/messages',{method:'POST',headers:{Origin:f.base,Cookie:member.client.cookie,'Content-Type':'application/json','Content-Length':Buffer.byteLength(delayedBody)}},res=>{res.resume();res.on('end',()=>resolve(res.statusCode));});delayedRequest.on('error',reject);delayedRequest.write(delayedBody.slice(0,1));});
  await started;await owner.call('/api/blocks','POST',{personId:member.user.id});delayedRequest.end(delayedBody.slice(1));assert.equal(await delayedResponse,403);observeRequest=null;
  assert.equal((await owner.call('/api/circles/'+c.id+'/messages')).body.messages.length,0);assert.equal((await member.client.call('/api/circles/'+c.id+'/messages')).status,403);
  await owner.call('/api/blocks/'+member.user.id,'DELETE');assert.equal((await member.client.call('/api/circles/'+c.id+'/leave','POST',{})).status,200);assert.equal((await member.client.call('/api/circles/'+c.id+'/messages','POST',{text:'After leaving'})).status,403);assert.equal((await owner.call('/api/circles/'+c.id+'/leave','POST',{})).status,400);
});

test('private meetup origins rank public venues and publish one bounded weekly series idempotently',async t=>{
  const folder=mkdtempSync(join(tmpdir(),'kaki-plans-')),dbPath=join(folder,'plans.sqlite'),f=await fixture(t,{dbPath});t.after(()=>rmSync(folder,{recursive:true,force:true}));const owner=f.client();await owner.call('/api/demo','POST',{});const member=await signupClient(f,'plan-member@ichat.sp.edu.sg'),outsider=await signupClient(f,'plan-outsider@ichat.sp.edu.sg'),foreign=f.client();await foreign.call('/api/demo','POST',{network:'university'});
  const c=(await owner.call('/api/circles','POST',{name:'Friday study club',interest:'Coding',description:'Study, build projects and meet new kakis.'})).body.circle;await member.client.call('/api/circles/'+c.id+'/join','POST',{});
  const p=(await owner.call('/api/circles/'+c.id+'/plans','POST',{title:'Weekly project catch-up',category:'study'})).body.plan;assert.equal(p.contributionCount,0);assert.equal(p.myPostalCode,null);assert.equal((await outsider.client.call('/api/plans/'+p.id)).status,403);assert.equal((await foreign.call('/api/plans/'+p.id)).status,404);
  assert.equal((await owner.call('/api/plans/'+p.id+'/origin','POST',{postalCode:'home'})).status,400);let result=await owner.call('/api/plans/'+p.id+'/origin','POST',{postalCode:'139651',lat:0,lng:0});assert.equal(result.status,200);assert.equal(result.body.plan.myPostalCode,'139651');assert.equal(result.body.plan.origins,undefined);assert.equal(result.body.plan.suggestions[0].id,'public-clementi-library');assert.equal(result.body.plan.ranking.ranked,false);const solo=(await member.client.call('/api/plans/'+p.id)).body.plan;assert.equal(solo.myPostalCode,null);assert.ok(solo.suggestions.every(v=>v.maxDistanceKm===undefined&&v.averageDistanceKm===undefined));assert.ok(!JSON.stringify(solo).includes('139651'));
  result=await member.client.call('/api/plans/'+p.id+'/origin','POST',{postalCode:'119077'});assert.equal(result.body.plan.contributionCount,2);assert.equal(result.body.plan.myPostalCode,'119077');assert.ok(!JSON.stringify(result.body).includes('139651'));const ownerView=(await owner.call('/api/plans/'+p.id)).body.plan;assert.equal(ownerView.myPostalCode,'139651');assert.ok(!JSON.stringify(ownerView).includes('119077'));assert.equal(ownerView.ranking.notTravelTime,true);assert.equal(ownerView.ranking.method,'minimax_straight_line');
  const body={venueId:ownerView.suggestions[0].id,title:'Weekly project catch-up',description:'Work through our project questions together.',category:'study',date:'2026-09-27',time:'15:30',capacity:8,weekly:true,occurrences:3,neighbourhoodOptIn:true};
  assert.equal((await member.client.call('/api/plans/'+p.id+'/publish','POST',body)).status,403);assert.equal((await owner.call('/api/plans/'+p.id+'/publish','POST',{...body,venueId:'private-home'})).status,400);assert.equal((await owner.call('/api/plans/'+p.id+'/publish','POST',{...body,occurrences:9})).status,400);assert.equal((await owner.call('/api/plans/'+p.id+'/publish','POST',{...body,weekly:false})).status,400);
  assert.equal((await owner.call('/api/plans/'+p.id+'/publish','POST',{...body,neighbourhoodOptIn:'yes'})).status,400);
  const published=await owner.call('/api/plans/'+p.id+'/publish','POST',body);assert.equal(published.status,201);assert.equal(published.body.plan.status,'published');assert.equal(published.body.plan.myPostalCode,null);assert.deepEqual(published.body.activities.map(a=>a.date),['2026-09-27','2026-10-04','2026-10-11']);assert.ok(published.body.activities.every(a=>a.time==='15:30'&&a.circleId===c.id&&a.network==='polytechnic'&&a.locationDetails.precision==='venue'&&a.neighbourhoodOptIn===true));const neighbourhood=(await member.client.call('/api/neighbourhood/events')).body.activities;assert.ok(published.body.activities.every(a=>neighbourhood.some(event=>event.id===a.id)));
  const repeat=await owner.call('/api/plans/'+p.id+'/publish','POST',body);assert.equal(repeat.status,200);assert.deepEqual(repeat.body.activities.map(a=>a.id),published.body.activities.map(a=>a.id));assert.equal((await owner.call('/api/plans/'+p.id+'/origin','POST',{postalCode:'139651'})).status,409);
  const db=new DatabaseSync(dbPath);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM plan_origins WHERE plan_id=?').get(p.id).n,0);db.close();const messages=(await member.client.call('/api/circles/'+c.id+'/messages')).body.messages;assert.equal(messages.filter(m=>m.type==='event').length,3);assert.ok(messages.filter(m=>m.type==='event').every(m=>m.activity?.circleId===c.id));assert.equal((await owner.call('/api/circles/'+c.id)).body.circle.weeklyEvents.length,3);
});

test('club origins can be removed and expire after seven days; non-contributors cannot publish',async t=>{
  const f=await fixture(t),c=f.client();await c.call('/api/demo','POST',{});const circle=(await c.call('/api/circles','POST',{name:'A new board-game club',interest:'Games',description:'An easy table for a friendly afternoon.'})).body.circle,plan=(await c.call('/api/circles/'+circle.id+'/plans','POST',{})).body.plan;
  const body={venueId:'public-clementi-library',title:'An easy afternoon',description:'An easy table for a friendly afternoon.',category:'games',date:'2026-09-20',time:'15:00',capacity:4,weekly:false,occurrences:1};assert.equal((await c.call('/api/plans/'+plan.id+'/publish','POST',body)).status,400);
  await c.call('/api/plans/'+plan.id+'/origin','POST',{postalCode:'139651'});assert.equal((await c.call('/api/plans/'+plan.id+'/origin','DELETE')).body.plan.contributionCount,0);await c.call('/api/plans/'+plan.id+'/origin','POST',{postalCode:'139651'});f.advance(7*86400000+1);await c.call('/api/demo','POST',{});const expired=(await c.call('/api/plans/'+plan.id)).body.plan;assert.equal(expired.contributionCount,0);assert.equal(expired.myPostalCode,null);assert.equal(expired.suggestions.length,0);
});

test('public mentor directory and profiles expose derived demo experience within privacy boundaries',async t=>{
  const folder=mkdtempSync(join(tmpdir(),'kaki-public-mentors-')),dbPath=join(folder,'mentors.sqlite'),f=await fixture(t,{dbPath});t.after(()=>rmSync(folder,{recursive:true,force:true}));const viewer=f.client(),anonymous=f.client();
  assert.equal((await anonymous.call('/api/mentors')).status,401);assert.equal((await anonymous.call('/api/mentors/polytechnic-p2')).status,401);
  for(const network of NETWORKS){const c=f.client();await c.call('/api/demo','POST',{network});const listing=await c.call('/api/mentors');assert.equal(listing.status,200);assert.deepEqual(listing.body.mentors.map(p=>p.id).sort(),[`${network}-p2`,`${network}-p4`]);assert.ok(listing.body.mentors.every(p=>p.network===network));assert.equal((await c.call('/api/mentors/'+(network==='university'?'polytechnic':'university')+'-p2')).status,404);}
  await viewer.call('/api/demo','POST',{});let alicia=(await viewer.call('/api/mentors/polytechnic-p2')).body.mentor,ryan=(await viewer.call('/api/mentors/polytechnic-p4')).body.mentor;
  assert.equal(alicia.name,'Alicia Tan');assert.equal(alicia.mentorStats.sessionCount,2);assert.equal(alicia.mentorStats.likeCount,2);assert.equal(alicia.mentorStats.daysSinceFirstMentorship,4);assert.equal(alicia.mentorStats.firstMentorshipAt,'2026-09-09T02:00:00.000Z');assert.equal(alicia.mentorStats.isNew,false);assert.equal(alicia.mentorStats.canLike,true);assert.equal(alicia.mentorStats.likedByMe,false);
  assert.equal(ryan.name,'Ryan Koh');assert.equal(ryan.mentorStats.registered,true);assert.equal(ryan.mentorStats.isNew,true);assert.equal(ryan.mentorStats.sessionCount,0);assert.equal(ryan.mentorStats.likeCount,0);assert.equal(ryan.mentorStats.firstMentorshipAt,null);assert.equal(ryan.mentorStats.daysSinceFirstMentorship,null);assert.equal(ryan.mentorStats.canLike,false);
  const allowed=new Set(['id','name','institutionId','institution','network','course','year','bio','avatar','interests','intentions','subjects','languages','studyStyle','availability','verified','verificationMethod','onboardingComplete','emailVerified','enrolmentVerified','ageVerified','mentorStats']);assert.ok(Object.keys(alicia).every(key=>allowed.has(key)));
  const db=new DatabaseSync(dbPath),read=(kind,id)=>JSON.parse(db.prepare('SELECT data FROM objects WHERE kind=? AND id=?').get(kind,id).data),write=(kind,p)=>db.prepare('UPDATE objects SET data=? WHERE kind=? AND id=?').run(JSON.stringify(p),kind,p.id);const raw=read('profile',alicia.id);raw.privateNotes='not public';raw.emergencyContact='not public';raw.reflections=[{text:'not public'}];write('profile',raw);
  const freshTutors=db.prepare('SELECT data FROM objects WHERE kind=?').all('tutor').map(row=>JSON.parse(row.data));assert.ok(freshTutors.length>0);assert.ok(freshTutors.every(tutor=>!Object.hasOwn(tutor,'rating')&&!Object.hasOwn(tutor,'sessionCount')));
  for(const id of ['polytechnic-t1','polytechnic-t2']){const legacy=read('tutor',id);legacy.rating=4.9;legacy.sessionCount=999;legacy.sessions=999;legacy.mentorStats={sessionCount:999,likeCount:999};write('tutor',legacy);}
  const oldActivity=read('activity','polytechnic-a2');oldActivity.title='My saved activity title';oldActivity.participants.push('polytechnic-p0');oldActivity.participantRoles['polytechnic-p0']='peer';write('activity',oldActivity);
  const restarted=createApi({dbPath});restarted.close();assert.equal(read('activity',oldActivity.id).title,'My saved activity title');assert.deepEqual(read('activity',oldActivity.id).participants,oldActivity.participants);assert.equal(db.prepare("SELECT COUNT(*) AS n FROM objects WHERE kind='activity' AND id LIKE 'polytechnic-mentor-%'").get().n,3);assert.equal(read('tutor','polytechnic-t1').rating,4.9);
  alicia=(await viewer.call('/api/mentors/polytechnic-p2')).body.mentor;for(const field of ['email','ageBand','settings','telegramUsername','privateNotes','emergencyContact','reflections','mentorshipRegisteredAt'])assert.equal(alicia[field],undefined,field);assert.equal(alicia.mentorStats.sessionCount,2);
  assert.equal((await viewer.call('/api/mentors/polytechnic-p2/like','POST',{})).body.mentorStats.likeCount,3);assert.equal((await viewer.call('/api/mentors/polytechnic-p2')).body.mentor.mentorStats.likedByMe,true);const likedTutor=(await viewer.call('/api/state')).body.tutors.find(t=>t.personId==='polytechnic-p2');assert.equal(likedTutor.mentorStats.likeCount,3);assert.equal(likedTutor.mentorStats.likedByMe,true);assert.equal((await viewer.call('/api/mentors/polytechnic-p2/like','POST',{})).body.mentorStats.likeCount,2);
  const state=(await viewer.call('/api/state')).body;assert.ok(state.tutors.every(t=>!Object.hasOwn(t,'rating')&&!Object.hasOwn(t.person,'rating')));assert.ok(state.tutors.every(t=>t.sessions===t.mentorStats.sessionCount&&t.sessionCount===t.person.mentorStats.sessionCount));assert.equal(state.tutors.find(t=>t.personId==='polytechnic-p2').sessions,2);assert.equal(state.tutors.find(t=>t.personId==='polytechnic-p2').mentorStats.likeCount,2);assert.equal(state.tutors.find(t=>t.personId==='polytechnic-p5').sessions,0);assert.equal(state.activities.find(a=>a.id==='polytechnic-mentor-history-1').demoHistorical,true);assert.equal((await viewer.call('/api/mentors/polytechnic-p7')).status,404);
  await viewer.call('/api/activities','POST',{category:'study',role:'mentor',title:'My first mentor session',description:'Let us work through a practice problem together.',date:'2026-09-14',time:'14:00',locationId:'sp-library',capacity:5});const preview=await viewer.call('/api/mentors/polytechnic-p0');assert.equal(preview.status,200);assert.equal(preview.body.mentor.email,undefined);assert.equal(preview.body.mentor.mentorStats.isNew,true);assert.ok((await viewer.call('/api/mentors')).body.mentors.every(p=>p.id!=='polytechnic-p0'));
  const younger=await signupClient(f,'mentor-younger@ichat.sp.edu.sg','under18');assert.equal((await younger.client.call('/api/mentors/polytechnic-p2')).status,403);assert.equal((await younger.client.call('/api/mentors')).body.mentors.length,0);
  raw.settings.discoverable=false;write('profile',raw);assert.equal((await viewer.call('/api/mentors/polytechnic-p2')).status,404);assert.ok((await viewer.call('/api/mentors')).body.mentors.every(p=>p.id!=='polytechnic-p2'));raw.settings.discoverable=true;write('profile',raw);db.close();
  await viewer.call('/api/blocks','POST',{personId:'polytechnic-p2'});assert.equal((await viewer.call('/api/mentors/polytechnic-p2')).status,403);assert.ok((await viewer.call('/api/mentors')).body.mentors.every(p=>p.id!=='polytechnic-p2'));
});

test('neighbourhood discovery requires host opt-in and preserves education, age and institution boundaries',async t=>{
  const f=await fixture(t),viewer=f.client(),anonymous=f.client();assert.equal((await anonymous.call('/api/neighbourhood/events')).status,401);
  for(const network of NETWORKS){const client=f.client();await client.call('/api/demo','POST',{network});const feed=await client.call('/api/neighbourhood/events');assert.equal(feed.status,200);assert.equal(feed.body.meta.scope,'neighbourhood');assert.equal(feed.body.meta.network,network);assert.equal(feed.body.meta.partnerImportsAvailable,false);assert.equal(feed.body.activities.length,42);assert.equal(new Set(feed.body.activities.map(a=>a.locationId)).size,10);assert.ok(new Set(feed.body.activities.map(a=>a.institutionId)).size>=5);assert.deepEqual([...new Set(feed.body.activities.map(a=>a.category))].sort(),['events','games','interests','lunch','sports','study']);for(const a of feed.body.activities){const venue=publicMeetingVenues.find(v=>v.id===a.locationId);assert.ok(venue);assert.equal(a.network,network);assert.equal(a.neighbourhoodOptIn,true);assert.equal(a.demoSample,true);assert.match(a.description,/fictional/i);assert.ok(a.date>='2026-09-13');assert.ok(a.participantCount<=a.capacity);assert.equal(a.institutionId,a.host.institutionId);assert.equal(a.institutionLabel,a.host.institution);assert.equal(a.locationDetails.precision,'venue');assert.equal(a.locationDetails.lat,venue.lat);assert.equal(a.locationDetails.lng,venue.lng);if(a.category==='study')assert.equal(a.roleCounts.peer+a.roleCounts.mentor,a.participantCount);}assert.ok(feed.body.activities.some(a=>a.category==='study'&&a.roleCounts.mentor===2));assert.ok(feed.body.activities.some(a=>a.participantCount===a.capacity));}
  await viewer.call('/api/demo','POST',{});const seed=(await viewer.call('/api/neighbourhood/events')).body.activities[0];assert.equal(seed.institutionId,'np');assert.equal(seed.institutionLabel,'Ngee Ann Polytechnic');assert.equal(seed.host.email,undefined);assert.equal((await viewer.call('/api/activities/'+seed.id+'/audience','POST',{neighbourhoodOptIn:false})).status,403);
  const np=await signupClient(f,'neighbourhood-host@connect.np.edu.sg','18plus','np'),younger=await signupClient(f,'neighbourhood-younger@ichat.sp.edu.sg','under18');
  const input={category:'interests',title:'A quiet neighbourhood meetup',description:'Bring a book and meet a few other students.',date:'2026-09-21',time:'14:00',locationId:'np-library',capacity:5,institutionId:'sp'};
  for(const value of ['true',null,1])assert.equal((await np.client.call('/api/activities','POST',{...input,neighbourhoodOptIn:value})).status,400);
  const created=await np.client.call('/api/activities','POST',input);assert.equal(created.status,201);const event=created.body.activity;assert.equal(event.institutionId,'np');assert.equal(event.neighbourhoodOptIn,false);assert.ok(!(await viewer.call('/api/neighbourhood/events')).body.activities.some(a=>a.id===event.id));assert.equal((await viewer.call('/api/activities/'+event.id)).status,200);
  assert.equal((await np.client.call('/api/activities/'+event.id+'/audience','POST',{})).status,400);assert.equal((await viewer.call('/api/activities/'+event.id+'/audience','POST',{neighbourhoodOptIn:true})).status,403);
  const optedIn=await np.client.call('/api/activities/'+event.id+'/audience','POST',{neighbourhoodOptIn:true,network:'university',institutionId:'ntu',hostId:'polytechnic-p0'});assert.equal(optedIn.status,200);assert.equal(optedIn.body.activity.network,'polytechnic');assert.equal(optedIn.body.activity.institutionId,'np');assert.equal(optedIn.body.activity.hostId,np.user.id);assert.ok((await viewer.call('/api/neighbourhood/events')).body.activities.some(a=>a.id===event.id));assert.equal((await viewer.call('/api/activities/'+event.id+'/join','POST',{})).status,200);
  assert.equal((await np.client.call('/api/activities/'+event.id+'/audience','POST',{neighbourhoodOptIn:false})).status,200);assert.ok(!(await viewer.call('/api/neighbourhood/events')).body.activities.some(a=>a.id===event.id));assert.equal((await viewer.call('/api/activities/'+event.id)).body.activity.joined,true);
  const young=await younger.client.call('/api/activities','POST',{...input,locationId:'sp-library',neighbourhoodOptIn:true});assert.equal(young.status,201);assert.ok(!(await viewer.call('/api/neighbourhood/events')).body.activities.some(a=>a.id===young.body.activity.id));assert.deepEqual((await younger.client.call('/api/neighbourhood/events')).body.activities.map(a=>a.id),[young.body.activity.id]);assert.equal((await younger.client.call('/api/activities/'+event.id+'/audience','POST',{neighbourhoodOptIn:true})).status,403);
  const foreign=f.client();await foreign.call('/api/demo','POST',{network:'university'});assert.ok((await foreign.call('/api/neighbourhood/events')).body.activities.every(a=>a.network==='university'));assert.equal((await foreign.call('/api/activities/'+event.id+'/audience','POST',{neighbourhoodOptIn:true})).status,404);
  await np.client.call('/api/activities/'+event.id+'/audience','POST',{neighbourhoodOptIn:true});await viewer.call('/api/blocks','POST',{personId:np.user.id});assert.ok(!(await viewer.call('/api/neighbourhood/events')).body.activities.some(a=>a.id===event.id));
});

test('rich demo migration is reproducible and preserves existing profiles, sessions and activity choices',async t=>{
  const folder=mkdtempSync(join(tmpdir(),'kaki-rich-seed-')),dbPath=join(folder,'rich.sqlite'),f=await fixture(t,{dbPath});t.after(()=>rmSync(folder,{recursive:true,force:true}));const account=await signupClient(f,'refresh-survivor@ichat.sp.edu.sg');
  await account.client.call('/api/profile','PATCH',{bio:'Keep my profile during a demo seed update.'});const existingId='polytechnic-neighbourhood-rich-01';assert.equal((await account.client.call('/api/activities/'+existingId+'/join','POST',{role:'peer'})).status,200);await account.client.call('/api/activities/'+existingId+'/save','POST',{});
  const custom=(await account.client.call('/api/activities','POST',{category:'interests',title:'My own saved gathering',description:'A small gathering created outside the demo seed.',date:'2026-09-22',time:'15:00',locationId:'sp-library',capacity:4,neighbourhoodOptIn:true})).body.activity;
  const db=new DatabaseSync(dbPath),read=(kind,id)=>JSON.parse(db.prepare('SELECT data FROM objects WHERE kind=? AND id=?').get(kind,id).data),write=(kind,p)=>db.prepare('UPDATE objects SET data=? WHERE kind=? AND id=?').run(JSON.stringify(p),kind,p.id);const edited=read('activity',existingId);edited.title='Keep the host’s edited sample title';edited.neighbourhoodOptIn=false;write('activity',edited);const host=read('profile',edited.hostId);host.bio='Keep this existing demo profile edit.';write('profile',host);
  db.prepare('DELETE FROM meta WHERE key=?').run('neighbourhood-rich-demo-v1');db.prepare('DELETE FROM objects WHERE kind=? AND id=?').run('activity','polytechnic-neighbourhood-rich-23');
  const migrated=createApi({dbPath,now:()=>Date.parse('2026-09-13T04:00:00Z')});migrated.close();const once=read('activity',existingId);assert.equal(once.title,edited.title);assert.equal(once.neighbourhoodOptIn,false);assert.deepEqual(once.participants,edited.participants);assert.equal(read('profile',host.id).bio,host.bio);assert.ok(read('activity','polytechnic-neighbourhood-rich-23'));assert.equal(read('activity',custom.id).title,custom.title);assert.equal(db.prepare("SELECT COUNT(*) AS n FROM objects WHERE kind='activity' AND id LIKE '%-neighbourhood-rich-%'").get().n,92);
  const restart=createApi({dbPath,now:()=>Date.parse('2026-09-13T04:00:00Z')});restart.close();assert.equal(db.prepare("SELECT COUNT(*) AS n FROM objects WHERE kind='activity' AND id LIKE '%-neighbourhood-rich-%'").get().n,92);db.close();const state=await account.client.call('/api/state');assert.equal(state.status,200);assert.equal(state.body.user.id,account.user.id);assert.equal(state.body.user.bio,'Keep my profile during a demo seed update.');assert.ok(state.body.user.savedActivityIds.includes(existingId));assert.equal(state.body.activities.find(a=>a.id===existingId).joined,true);
  const jamie=f.client();await jamie.call('/api/demo','POST',{});const club=(await jamie.call('/api/circles/polytechnic-c2')).body.circle;assert.equal(club.joined,true);const messages=(await jamie.call('/api/circles/polytechnic-c2/messages')).body.messages;assert.equal(messages.filter(m=>m.type==='message').length,3);const plan=(await jamie.call('/api/plans/polytechnic-demo-plan')).body.plan;assert.equal(plan.status,'draft');assert.equal(plan.contributionCount,2);const mentors=(await jamie.call('/api/mentors')).body.mentors;assert.equal(mentors.find(p=>p.id==='polytechnic-p2').mentorStats.sessionCount,2);assert.equal(mentors.find(p=>p.id==='polytechnic-p4').mentorStats.isNew,true);assert.equal((await jamie.call('/api/activities/polytechnic-a2')).body.activity.participantRoles['polytechnic-p2'],'mentor');
});

